import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const dubai = localFont({
  src: [
    {
      path: "../public/fonts/Dubai-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Dubai-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Dubai-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-dubai",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={dubai.className}>{children}</body>
    </html>
  );
}
